config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # resource :myprofile, only: [:new, :create]
  get '/profile', to: 'myprofile#new'
  post '/profile', to: 'myprofile#create'
  get '/my_profile', to: 'myprofile#show' , as: 'show_my_profile'

  root 'home#index'
  get '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  # post '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  get '/feed', to: 'myprofile#feed'
  post '/create/image', to: 'myprofile#create_image'

  resources :friend_requests, only: [:index, :new, :create, :show, :update, :destroy]
  resources :group_chats, only: [:index, :show, :new, :create]

  resources :messages
  mount ActionCable.server, at: '/cable'

  resources :group_chats do
    resources :messages
  end


end

app/models/my_profile.rb
class MyProfile < ApplicationRecord
    belongs_to :user
end

app/controllers/myprofile_controller.rb
class MyprofileController < ApplicationController
    
  before_action :authenticate_user!, only: [:new, :create , :show, :upload_image , :feed]

  def new
    @my_profile = current_user.build_my_profile
  end

  def create
    @my_profile = current_user.build_my_profile(profile_params)

    if @my_profile.save
      flash[:success] = "Profile successfully created!"
      redirect_to show_my_profile_path
    else
      flash.now[:error] = "Error creating profile, Please check the form"
      render new
    end

  end

  def feed
    @feed_posts = Post.includes(user: [:my_profile], images: [file_attachment: :blob]).order(created_at: :desc)
   

  end
  def show
    @my_profile = current_user.my_profile
  end

  def upload_image
    @user = current_user
  end

  def create_image
    puts "inside create function image"
    @user = current_user
    @post = @user.build(post_params)
    puts "this is file #{@post}"
    @post.images.file = @post.file
  
    if @post.save
      flash[:success] = "Image uploaded successfully"
      redirect_to feed_path
    else
      flash.now[:error] = "Error uploading image, please check the form"
      render :upload_image
    end
  end
  
  private
  
  def post_params
    params.require(:user).permit(:caption, :file)
  end
  
  


  def profile_params
    params.require(:my_profile).permit(:fname, :user_name , :age , :birthdate , :gender , :bio , :mobile , :address)
  end  

  
end
  

app/helpers/myprofile_helper.rb
module MyprofileHelper
end

app/views/myprofile/feed.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <h2>Feed</h2>
  puts "outside if condition"
  
  <% if @feed_posts.present? %>
  <%= puts "inside if condition" %>
  
    <% @feed_posts.each do |post| %>
      <div class="card mb-3">
        <div class="card-body">
          <% if post.user.present? && post.user.my_profile.present? %>
            <h4 class="card-title"><%= post.user.my_profile.user_name %></h4>
          <% else %>
            <p class="text-danger">User profile not found for this post.</p>
          <% end %>

          <p class="card-text"><%= post.comment %></p>

          <% if @feed_posts.present? %>
            <% @feed_posts.images.each do |image| %>
              <%= image_tag(image.file, class: "img-fluid") %>
            <% end %>
          <% end %>


          
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>No posts yet</h3>
  <% end %>

</div>

app/views/myprofile/new.html.erb
<h1> Profile </h1>

<%= form_with(model: @my_profile, url: profile_path, local: true) do |form| %>
    <div class= "field">
        <%= form.label :fname %>
        <%= form.text_field :fname, required: true %>
    </div>

    <div class="field">
        <%= form.label :user_name %>
        <%= form.text_field :user_name %>
    </div>
    <div class="field">
        <%= form.label :age %>
        <%= form.text_field :age %>
    </div>
    <div class="field">
        <%= form.label :birthdate %>
        <%= form.date_field :birthdate %>
    </div>
    <div class="field">
        <%= form.label :gender %>
        <%= form.text_field :gender %>
    </div>
    <div class="field">
        <%= form.label :bio %>
        <%= form.text_field :bio %>
    </div>
    <div class="field">
        <%= form.label :mobile %>
        <%= form.text_field :mobile %>
    </div>
    <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address %>
    </div>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
    <div class="actions">
      <%= form.submit "Create User Detail", class: "green-button-style" %>
    </div>
<% end %>

app/views/myprofile/show.html.erb
<h2> Your Profile Details </h2>

<p><strong>User ID: </strong> <%= current_user.id %> </p>
<p><strong>Name: </strong> <%= @my_profile.fname %> </p>
<p><strong>User Name: </strong> <%= @my_profile.user_name %> </p>
<p><strong>Bio: </strong> <%= @my_profile.bio %> </p>
<p><strong>DOB: </strong> <%= @my_profile.birthdate %> </p>
<p><strong>Gender: </strong> <%= @my_profile.gender %> </p>
<p><strong>Mobile: </strong> <%= @my_profile.mobile %> </p>
<p><strong>Address: </strong> <%= @my_profile.address %> </p>
<p><strong>Email: </strong> <%= @my_profile.email %> </p>

<% if user_signed_in? %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <%= link_to 'Go to Feed', feed_path, class: 'btn btn-primary' %>
<% else %>
    <%= link_to 'Log In', new_user_session_path, class: 'green-button-style' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'button-style float-end' %>
<% end %>

app/views/myprofile/upload_image.html.erb
<%= form_with(model: @user, url: create_image_path, method: :post, local: true, multipart: true) do |form| %>
  <div class="mb-3">
    <%= form.label :file, class: "form-label" %>
    <%= form.file_field :file, class: "form-control", multiple: true %>
  </div>
  <div class="mb-3">
    <%= form.label :caption, class: "form-label" %>
    <%= form.text_area :caption, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Upload Image", class: "btn btn-primary" %>
  </div>
<% end %>