config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # resource :myprofile, only: [:new, :create]
  get '/profile', to: 'myprofile#new'
  post '/profile', to: 'myprofile#create'
  get '/my_profile', to: 'myprofile#show' , as: 'show_my_profile'

  root 'home#index'
  get '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  # post '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  get '/feed', to: 'myprofile#feed'
  post '/create/image', to: 'myprofile#create_image'

  resources :friend_requests, only: [:index, :new, :create, :show, :update, :destroy]
  resources :group_chats, only: [:index, :show, :new, :create]

  resources :messages
  mount ActionCable.server, at: '/cable'

  resources :group_chats do
    resources :messages
  end


end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
    has_many :messages
end

app/controllers/group_chats_controller.rb
class GroupChatsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @group_chats = GroupChat.all
    end
  
    def show
      @group_chat = GroupChat.find(params[:id])
      @messages = @group_chat.messages.order(created_at: :asc)
      @new_message = @group_chat.messages.build # Build a new message for the form
    end
  
    def new
      @group_chat = GroupChat.new
    end
  
    def create
      @group_chat = GroupChat.new(group_chat_params)
      if @group_chat.save
        flash[:notice] = "Group chat created successfully."
        redirect_to group_chats_path
      else
        flash[:alert] = "Group chat could not be created."
        render :new
      end
    end
  
    private
  
    def group_chat_params
      params.require(:group_chat).permit(:name)
    end
  end
  

app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

app/views/group_chats/index.html.erb
<!-- app/views/group_chats/index.html.erb -->
<h1>Group Chats</h1>

<% @group_chats.each do |group_chat| %>
  <%= link_to group_chat.name, group_chat_path(group_chat) %><br>
<% end %>

app/views/group_chats/new.html.erb
<!-- app/views/group_chats/new.html.erb -->

<h1>Create a New Group</h1>

<%= form_for @group_chat do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Group Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Create Group', class: 'btn btn-primary' %>
<% end %>

app/views/group_chats/show.html.erb
<!-- app/views/group_chats/show.html.erb -->
<h1><%= @group_chat.name %></h1>

<div id="group-chat">
  <!-- Display group chat messages here -->
  <% @messages.each do |message| %>
    <p><strong><%= message.user.email %>:</strong> <%= message.content %></p>
  <% end %>
</div>

<!-- Form to submit a new message -->
<%= form_with(model: [@group_chat, @new_message], url: group_chat_messages_path(@group_chat), method: :post) do |form| %>
  <%= form.text_area :content, class: 'form-control' %>
  <%= form.submit 'Send Message', class: 'btn btn-primary mt-2' %>
<% end %>