config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # resource :myprofile, only: [:new, :create]
  get '/profile', to: 'myprofile#new'
  post '/profile', to: 'myprofile#create'
  get '/my_profile', to: 'myprofile#show' , as: 'show_my_profile'

  root 'home#index'
  get '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  # post '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  get '/feed', to: 'myprofile#feed'
  post '/create/image', to: 'myprofile#create_image'

  resources :friend_requests, only: [:index, :new, :create, :show, :update, :destroy]
  resources :group_chats, only: [:index, :show, :new, :create]

  resources :messages
  mount ActionCable.server, at: '/cable'

  resources :group_chats do
    resources :messages
  end


end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    before_action :authenticate_user!

    def index
      @friend_requests = current_user.received_friend_requests
    end
  
    def new
      @recipient = User.find(params[:recipient_id])
      @friend_request = FriendRequest.new
    end
  
    def create
      friend = User.find(params[:friend_id])
      if current_user.send_friend_request(friend)
        flash[:notice] = "Friend request sent successfully."
      else
        flash[:alert] = "Friend request could not be sent."
      end
      redirect_back(fallback_location: root_path)
    end
  
    def update
      friend_request = FriendRequest.find(params[:id])
      if current_user.accept_friend_request(friend_request)
        flash[:notice] = "Friend request accepted."
      else
        flash[:alert] = "Friend request could not be accepted."
      end
      redirect_back(fallback_location: root_path)
    end
  
    def show
      @friend_request = FriendRequest.find(params[:id])
    end

    def destroy
      friend_request = FriendRequest.find(params[:id])
      if current_user.reject_friend_request(friend_request)
        flash[:notice] = "Friend request rejected."
      else
        flash[:alert] = "Friend request could not be rejected."
      end
      redirect_back(fallback_location: root_path)
    end
end
  

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<!-- app/views/friend_requests/_form.html.erb -->
<%= form_with model: friend_request do |form| %>
  <!-- form fields go here -->
<% end %>

app/views/friend_requests/index.html.erb
<!-- app/views/friend_requests/index.html.erb -->
<h1>Friend Requests</h1>

<% @friend_requests.each do |request| %>
  <p>
    <%= "#{request.sender.email} sent a friend request to #{request.recipient.email}" %>
    <%= link_to 'Accept', friend_request_path(request), method: :put %>
    <%= link_to 'Reject', friend_request_path(request), method: :delete %>
  </p>
<% end %>

app/views/friend_requests/new.html.erb
<!-- app/views/friend_requests/new.html.erb -->
<h1>New Friend Request</h1>

<%= form_with model: FriendRequest.new, url: friend_requests_path, method: :post do |form| %>
  <%= form.hidden_field :recipient_id, value: @recipient.id %>
  <%= form.submit 'Send Friend Request' %>
<% end %>

app/views/friend_requests/show.html.erb
<!-- app/views/friend_requests/show.html.erb -->
<h1>Friend Request Details</h1>

<p>
  <%= "#{@friend_request.sender.email} sent a friend request to #{@friend_request.recipient.email}" %>
</p>