config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # resource :myprofile, only: [:new, :create]
  get '/profile', to: 'myprofile#new'
  post '/profile', to: 'myprofile#create'
  get '/my_profile', to: 'myprofile#show' , as: 'show_my_profile'

  root 'home#index'
  get '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  # post '/upload_image', to: 'myprofile#upload_image', as: 'upload_image'
  get '/feed', to: 'myprofile#feed'
  post '/create/image', to: 'myprofile#create_image'

  resources :friend_requests, only: [:index, :new, :create, :show, :update, :destroy]
  resources :group_chats, only: [:index, :show, :new, :create]

  resources :messages
  mount ActionCable.server, at: '/cable'

  resources :group_chats do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :friend
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
    has_many :messages
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
  has_one_attached :file
  validates :file, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :friend_request, optional: true
  belongs_to :group_chat
end

app/models/my_profile.rb
class MyProfile < ApplicationRecord
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :comment, presence: true
  validates_associated :images
end

app/models/user.rb
class User < ApplicationRecord
  has_one :my_profile
  has_many_attached :images
  has_many :posts
  has_many :friendships
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: 'sender_id'
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: 'recipient_id'
  has_many :friends, through: :friendships
  has_many :group_chats, through: :group_memberships

  def send_friend_request(recipient)
    sent_friend_requests.create(recipient: recipient)
  end

  def accept_friend_request(friend_request)
    friendship = Friendship.create(user: self, friend: friend_request.sender, accepted: true)
    friend_request.update(accepted: true)
    friendship.valid? && friend_request.valid?
  end

  def reject_friend_request(friend_request)
    friend_request.update(accepted: false)
  end
  

  validates :caption, length: { maximum: 255 }
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    before_action :authenticate_user!

    def index
      @friend_requests = current_user.received_friend_requests
    end
  
    def new
      @recipient = User.find(params[:recipient_id])
      @friend_request = FriendRequest.new
    end
  
    def create
      friend = User.find(params[:friend_id])
      if current_user.send_friend_request(friend)
        flash[:notice] = "Friend request sent successfully."
      else
        flash[:alert] = "Friend request could not be sent."
      end
      redirect_back(fallback_location: root_path)
    end
  
    def update
      friend_request = FriendRequest.find(params[:id])
      if current_user.accept_friend_request(friend_request)
        flash[:notice] = "Friend request accepted."
      else
        flash[:alert] = "Friend request could not be accepted."
      end
      redirect_back(fallback_location: root_path)
    end
  
    def show
      @friend_request = FriendRequest.find(params[:id])
    end

    def destroy
      friend_request = FriendRequest.find(params[:id])
      if current_user.reject_friend_request(friend_request)
        flash[:notice] = "Friend request rejected."
      else
        flash[:alert] = "Friend request could not be rejected."
      end
      redirect_back(fallback_location: root_path)
    end
end
  

app/controllers/group_chats_controller.rb
class GroupChatsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @group_chats = GroupChat.all
    end
  
    def show
      @group_chat = GroupChat.find(params[:id])
      @messages = @group_chat.messages.order(created_at: :asc)
      @new_message = @group_chat.messages.build # Build a new message for the form
    end
  
    def new
      @group_chat = GroupChat.new
    end
  
    def create
      @group_chat = GroupChat.new(group_chat_params)
      if @group_chat.save
        flash[:notice] = "Group chat created successfully."
        redirect_to group_chats_path
      else
        flash[:alert] = "Group chat could not be created."
        render :new
      end
    end
  
    private
  
    def group_chat_params
      params.require(:group_chat).permit(:name)
    end
  end
  

app/controllers/messages_controller.rb
# app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @group_chat = GroupChat.find(params[:group_chat_id])
    @message = @group_chat.messages.create(message_params)
    redirect_to group_chat_path(@group_chat)
  end

  private

  def message_params
    params.require(:message).permit(:content, :user_id)
  end
end

app/controllers/myprofile_controller.rb
class MyprofileController < ApplicationController
    
  before_action :authenticate_user!, only: [:new, :create , :show, :upload_image , :feed]

  def new
    @my_profile = current_user.build_my_profile
  end

  def create
    @my_profile = current_user.build_my_profile(profile_params)

    if @my_profile.save
      flash[:success] = "Profile successfully created!"
      redirect_to show_my_profile_path
    else
      flash.now[:error] = "Error creating profile, Please check the form"
      render new
    end

  end

  def feed
    @feed_posts = Post.includes(user: [:my_profile], images: [file_attachment: :blob]).order(created_at: :desc)
   

  end
  def show
    @my_profile = current_user.my_profile
  end

  def upload_image
    @user = current_user
  end

  def create_image
    puts "inside create function image"
    @user = current_user
    @post = @user.build(post_params)
    puts "this is file #{@post}"
    @post.images.file = @post.file
  
    if @post.save
      flash[:success] = "Image uploaded successfully"
      redirect_to feed_path
    else
      flash.now[:error] = "Error uploading image, please check the form"
      render :upload_image
    end
  end
  
  private
  
  def post_params
    params.require(:user).permit(:caption, :file)
  end
  
  


  def profile_params
    params.require(:my_profile).permit(:fname, :user_name , :age , :birthdate , :gender , :bio , :mobile , :address)
  end  

  
end
  

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/myprofile_helper.rb
module MyprofileHelper
end

app/views/home/index.html.erb
<h1> This is the home page </h1>

app/views/layouts/_chat_section.html.erb
<!-- app/views/layouts/_chat_section.html.erb -->
<div id="chat-section" class="container mt-4">
  <div class="row">
    <!-- User List -->
    <div class="col-md-4">
      <h4>Users</h4>
      <ul class="list-group">
        <!-- Add users dynamically -->
        <li class="list-group-item">User 1</li>
        <li class="list-group-item">User 2</li>
        <!-- ... -->
      </ul>
    </div>

    <!-- Chat Area -->
    <div class="col-md-8">
      <h4>Chat</h4>
      <div id="chat-messages" class="border rounded p-3" style="height: 300px; overflow-y: scroll;">
        <!-- Display chat messages dynamically -->
        <p><strong>User 1:</strong> Hi there!</p>
        <p><strong>User 2:</strong> Hello!</p>
        <!-- ... -->
      </div>

      <!-- Message Input Form -->
      <%= form_with(model: Message.new, url: messages_path, method: :post) do |form| %>
        <div class="input-group mt-3">
          <%= form.text_area :content, class: 'form-control', placeholder: 'Type your message...' %>
          <div class="input-group-append">
            <%= form.submit 'Send', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->
<nav class="navbar navbar-expand navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Your Logo', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Upload Image', upload_image_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Profile', show_my_profile_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Feed', feed_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create Group Chat', new_group_chat_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_request_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
  </head>

  <body>
   
    <%= yield %>
    
    <script src="<%= asset_path('channels/chat_channel.js') %>"></script>
    <script src="C:Users/hp/OneDrive/Desktop/FriendFolio/app/javascript/channels/chat_channel.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>